apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - name: log-sidecar
        image: busybox
        command: ["sh", "-c"]
        args:
        - while true; do
            echo sync application logs;
            printenv NODE_NAME POD_NAME POD_SERVICE_ACCOUNT POD_IP_ADDRESS;
            sleep 20;
          done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      initContainers:
      - name: db-availablity
        image: busybox
        command: ["sh", "-c", "until nslookup mydb-service; do echo waiting for database; sleep 4; done"]
