apiVersion: v1
kind: Service
metadata:
  labels:
    app: mydb-service
  name: mydb-service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mydb-service
  type: ClusterIP
